# Generated by Django 5.0 on 2023-12-17 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_requests_received', models.ManyToManyField(blank=True, related_name='received_friend_requests', to='app.userprofile')),
                ('friend_requests_sent', models.ManyToManyField(blank=True, related_name='sent_friend_requests', to='app.userprofile')),
                ('friends', models.ManyToManyField(blank=True, to='app.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
